name: Update gh-pages

on:
  workflow_run:
    workflows: [ Java CI ]
    types: [ completed ]
    branches: [ main ]

jobs:
  generate-docs-reports:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Export project version
        run: echo "PROJECT_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Run tests and Generate reports
        run: ./mvnw --no-transfer-progress --batch-mode test site

      - name: Deploy maven reports to GitHub Pages as current version
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          clean: true
          folder: target/site
          target-folder: docs/${{ env.PROJECT_VERSION }}/site

      - name: Deploy maven reports to GitHub Pages as latest version
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          clean: true
          folder: target/site
          target-folder: docs/latest/site
